"""
This class is responsible for text embedding models used to evaluate the similarity between the VLM generated responses and the adversary's target answer
"""

from strenum import StrEnum
from transformers import AutoModel
import torch

class TextEmbedderName(StrEnum):
    JINA_TEXT_V3 = "jinaai/jina-embeddings-v3"


class TextEmbeddingModel:
    
    def __init__(self, model_name: str, device):
        self.name = model_name

        if model_name == TextEmbedderName.JINA_TEXT_V3:
            self.model = AutoModel.from_pretrained(
                model_name,
                torch_dtype=torch.float32 if device == "mps" else "auto",
                trust_remote_code=True).to(device)
            self.processor = None
            self.tokenizer = None
        
        self.model.requires_grad_(False)
        self.model.eval()

    @torch.no_grad()
    def compare_embeddings(self, generated_strs: list[str], target_answer: str, similarity_metric: str):
        self.model.eval()
        if type(target_answer) == str: target_answer = [target_answer]
        if type(generated_strs) == str: generated_strs = [generated_strs]

        generated_embedding = self.compute_embeddings(generated_strs)        
        target_embedding = self.compute_embeddings(target_answer)

        return self.compute_similarity(generated_embedding, target_embedding, similarity_metric)
    
    def compute_embeddings(self, texts: list[str]):
        if self.name == TextEmbedderName.JINA_TEXT_V3:
            return self.model.encode(texts, task="text-matching")
        
        raise ValueError(f"Unsupported text embedding model name '{self.name}'.")
    
    def compute_similarity(self, generated_embeddings, target_embeddings, similarity_metric: str):
        """
        NOTE: embeddings generated by Jina are numpy arrays by default
        """
        if similarity_metric == "cos":
            return generated_embeddings @ target_embeddings.T
        
        raise ValueError(f"Unsupported similarity metric '{similarity_metric}'.")